/* Drop TABLE  */
DROP TABLE Reservation CASCADE CONSTRAINTS;
DROP TABLE Affectation CASCADE CONSTRAINTS;
DROP TABLE Vol CASCADE CONSTRAINTS;
DROP TABLE Avion CASCADE CONSTRAINTS;
DROP TABLE Appareil CASCADE CONSTRAINTS;
DROP TABLE Aeroport CASCADE CONSTRAINTS;

/* Drop SEQUENCE  */

DROP SEQUENCE reserv_auto_inc;
DROP SEQUENCE affect_auto_inc;
DROP SEQUENCE avion_auto_inc;
